eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8704
###################  spring配置  ###################
spring:
  application:
    name: service-feign
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/mis?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      filters: log4j,wall,mergeStat
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views
      suffix: .html
  http:
    converters:
      preferred-json-mapper: json
  devtools:
    restart:
      enabled: false
  thymeleaf:
       cache: false
       mode: LEGACYHTML5